### ISSUE TITLE
Gap Duration Analysis:

### ISSUE THREAD

**Issue by nuzhat5** [avenueconsultants/ATSPM#26]
* Acceptable gaps should be SumGapDuration1 divided by 4.1 (if critical gap = 4.1) or SumGapDuration2 divided by 5.3 (if critical gap = 5.3); Line 60, LeftTurnGapOutAnalysis.cs
* Line 48, LeftTurnGapOutAnalysis.cs needs to be Demand divided by Capacity. So it will be  - gapDurationResult.GapDurationPercent = gapDurationResult.Demand / gapDurationResult.Capacity;

**Comment by avetraffic** [comment]
Looks fixed
