### ISSUE TITLE
LeftTurnReportPreCheck:

### ISSUE THREAD

**Issue by nuzhat5** [avenueconsultants/ATSPM#28]
* tempDate: The tempDates are picking up datetime input from input and adding peak hour time to it. So if someone puts in StartDate = 01/09/2020 06:00:00, the peak hour (AM) will turn into 06:00:00 + 7:30 = 13:30:00. We want the peak hour to be 07:30:00.
* Solution: Nuzhat is working on finding a solution

**Comment by avetraffic** [comment]
non-issue
